### ISSUE TITLE
关于Dis损失的问题？

### ISSUE THREAD

**Issue by xiaomingdaren123** [aftercloud/MA-CNN#1]
有一点不太理解，想请教一下：
1、di(x)这个权重矩阵是不是要先训练出来，使特征图属于某一part时权重为，不属于时权重为0？
2、Dis(Mi)这个损失函数中的tx,ty就是得到的mask特征图中最大值的索引坐标？这个函数是怎么达到让相同part内的坐标更聚集？

**Comment by aftercloud** [comment]
第一个问题，需要预训练，聚类和分类是交替训练的
第二个问题，是最大值的索引坐标，每次迭代，相同part内的坐标会向最大值的方向聚集
