### ISSUE TITLE
diversity loss

### ISSUE THREAD

**Issue by shuxjweb** [aftercloud/MA-CNN#2]
1、part_macnn.py  文件中loss类中求div部分被您注释掉，请问里面的x是什么？它的shape好像是4个维度，但您在forward(self, tensor)中输入的tensor是3个维度，x好像不是tensor，请问是什么
2、output = part(channels)，这里的output的shape是[batch, 28, 28]，请问output代表什么含义，是每个样本的attention吗？

**Comment by sucaohan** [comment]
您好 我想请问下loss的div中的mgr是啥意思啊 求解代码好像是归一化的意思？？ 为什么有了他就能保证求到多样化的注意力特征呢？就是div的损失函数能否解释一下呢？

**Comment by aftercloud** [comment]
1. div中的x是n层28x28的attention，part的输出是attention
2. mgr的话我记得论文里面是有的，就是损失值来着
3. 需要注意力的话，可以看看更容易理解也更好实现的SE-Net
