### ISSUE TITLE
同学 请教一下多分组的问题

### ISSUE THREAD

**Issue by sucaohan** [aftercloud/MA-CNN#3]
同学，我看你写的代码里只分了一组，那么多分组应该怎么分类扩充呢？原文中是对每个通道进行特征表示，然后通过多个全连接层得到每个通道对应的权重，请问该如何改呢？十分困惑，望同学指点一二

**Comment by aftercloud** [comment]
一个part就是一组，多分组需要在part外面再封装一层
原始论文的模型用的是caffe，caffe的网络结构可以使用web直接可视化，如果确实需要的话，参照着改一改就好了
如果要用注意力机制，可以考虑一下更容易实现也更容易理解的SE-Net
