### ISSUE TITLE
数据文件还有吗？

### ISSUE THREAD

**Issue by li-123156** [aftercloud/MA-CNN#4]

**Comment by aftercloud** [comment]
数据文件没有啦，映象中是一组人脸数据来着，需要用注意力的话，可以看看更容易理解和实现的SE-Net

**Comment by li-123156** [comment]
冒昧打扰。
首先多谢您对我关于数据文件的问题进行解答，但是关于macnn代码实现还有几个问题想要请教您。
在您的代码中若想实现多个注意力区域的话，需要对Part类进行更改吗？在我的理解中，可以多次使用Part函数实现多个注意力区域实现，但是之后有多个区域后怎样进行对注意力区域进行拼接参与损失计算及怎样进行反向传播更新参数仍然没有想明白，所以冒昧发邮件向您请教。












------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aftercloud/MA-CNN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月24日(星期天) 晚上7:53
收件人:&nbsp;"aftercloud/MA-CNN"<MA-CNN@noreply.github.com&gt;;
抄送:&nbsp;"李子."<2694982289@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [aftercloud/MA-CNN] 数据文件还有吗？ (#4)





 
数据文件没有啦，映象中是一组人脸数据来着，需要用注意力的话，可以看看更容易理解和实现的SE-Net
